### ISSUE TITLE
[Bug Report] You can use mending on the Totem of Neverdying (also unbreaking)

### ISSUE THREAD

**Issue by Aruman-Zen** [SLH335/netherite-extras#2]
i'm not sure if is intended but it makes the totem overpowered and the 4 uses mechanic meaningless
![image](https://github.com/SLH335/netherite-extras/assets/159113965/dacbbfb3-d2e8-4bfa-8708-fce456d81e65)

**Comment by SLH335** [comment]
Thanks for reporting this issue!
That behavior was indeed not intentional. Mending and Unbreaking can be applied to any item with durability by default, which I wasn't aware of before. It should be fixed in the latest release [v0.2.2](https://modrinth.com/mod/netherite-extras/version/0.2.2+mc1.20.1).
