### ISSUE TITLE
[Question] Changing mod textures

### ISSUE THREAD

**Issue by MrMcSiber** [SLH335/netherite-extras#3]
Im a total beginner at modding and wanted to change the textures... But i dont know how to build the file. Please help me. Even the Internet lost its hope. I just dont know how

**Comment by SLH335** [comment]
If you only want to change textures and don't plan on changing the functionality of the mod itself, you can use a resource pack to do that. Building the mod from source is not required in that case. There are plenty of tutorials on how to create your own resource pack online. When changing textures for a mod, you have to use the Mod ID (`netheriteextras` for this mod) as the name of the asset directory instead of `minecraft`.

If you want to change the texture of the Netherite Nugget, for example, you would store the image in the following location:
`<Your Pack Name>/assets/netheriteextras/textures/item/netherite_nugget.png`

If you are unsure where the textures are stored, you can follow the structure of the assets in the mod's source code:
https://github.com/SLH335/netherite-extras/tree/main/src/main/resources/assets/netheriteextras

**Comment by SLH335** [comment]
As there isn't any activity, I will assume you were able to resolve your issue. If you have further questions regarding this, feel free to ask here.
